commands = {
    "create_circle": [
        "create a circle",
        "I want a circle",
        "add a circle",
        "add circle",
        "create circle",
        "make a circle",
        "draw a circle",
        "add a round shape",
        "create a round shape",
        "make a round shape",
        "add a round object",
        "create an oval",
        "make an oval",
        "add an oval",
        "draw an oval",
        "put a circle here",
        "put a circle on the screen",
        "add a round shape here",
        "make something round",
        "create something round",
        "draw something round",
        "I need a circle",
        "I need a round shape",
        "I need an oval",
        "give me a circle",
        "give me an oval",
        "give me a round shape",
        "can you create a circle",
        "can you make a circle",
        "can you add a circle",
        "can you draw a circle",
        "can you create an oval",
        "can you make an oval",
        "can you add an oval",
        "can you draw an oval",
        "let's create a circle",
        "let's make a circle",
        "let's add a circle",
        "let's draw a circle",
        "let's create an oval",
        "let's make an oval",
        "let's add an oval",
        "let's draw an oval",
        "I want to add a circle",
        "I want to create a circle",
        "I want to make a circle",
        "I want to draw a circle",
        "I want to add an oval",
        "I want to create an oval",
        "I want to make an oval",
        "I want to draw an oval",
        "put down a circle",
        "put down an oval",
        "place a circle",
        "place an oval",
        "place a round shape",
        "add something circular",
        "create something circular",
        "make something circular",
        "draw something circular",
        "add a circular shape",
        "create a circular shape",
        "make a circular shape",
        "draw a circular shape",
        "add a round object",
        "create a round object",
        "make a round object",
        "draw a round object",
        "add a disk",
        "create a disk",
        "make a disk",
        "draw a disk",
        "add a disc",
        "create a disc",
        "make a disc",
        "draw a disc",
        "add a round",
        "create a round",
        "make a round",
        "draw a round",
        "add a round figure",
        "create a round figure",
        "make a round figure",
        "draw a round figure",
        "add a circular object",
        "create a circular object",
        "make a circular object",
        "draw a circular object",
        "I want something circular",
        "I want something round",
        "I want something oval",
        "give me something circular",
        "give me something round",
        "give me something oval",
        "put something circular here",
        "put something round here",
        "make it a circle",
        "make it round"
    ],
    "move_circle": ["move the circle", "shift the circle", "drag the circle"],
}

